// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// A URL e a anon key do Supabase são valores PÚBLICOS por design.
// A segurança é garantida pelo RLS (Row Level Security) no banco de dados.
// Referência: https://supabase.com/docs/guides/api/api-keys
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL
  ?? "https://jqtlolabtiekqqnxdomf.supabase.co";

const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY
  ?? "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxdGxvbGFidGlla3Fxbnhkb21mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc3Mzk2ODksImV4cCI6MjA5MzMxNTY4OX0.G5NHq3H7ba4mVjwrhzXNEOcfTyLHGvdr2mHPZk6SpgE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});